# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-31 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20)),
                ('date_sold', models.DateField()),
                ('predicted', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20)),
                ('date_sold', models.DateField()),
                ('predicted', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='customer_order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app.House_Product'),
        ),
        migrations.AlterField(
            model_name='house_product',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='app.Product'),
        ),
    ]
