# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-06 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='second_name',
            field=models.CharField(default='bright', max_length=10),
            preserve_default=False,
        ),
    ]
