# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-29 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(default='email@example.com', max_length=30),
        ),
    ]
