# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-06 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190806_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.CharField(default='email@example.com', max_length=50),
            preserve_default=False,
        ),
    ]
