# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-23 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190722_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_product',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
