# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-06 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_requested_supply'),
    ]

    operations = [
        migrations.AddField(
            model_name='requested_supply',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
