# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-10 06:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190731_1935'),
        ('app', '0005_requested_supply_quantity'),
    ]

    operations = [
    ]
