# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-23 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190723_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='serial',
            new_name='sKU',
        ),
        migrations.AddField(
            model_name='house_product',
            name='sKU',
            field=models.CharField(default='I', max_length=10),
        ),
    ]
