# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-23 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190723_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor_sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sKU', models.CharField(max_length=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Product')),
                ('warehouse', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Distributor')),
            ],
        ),
    ]
