# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-24 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_distributor_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor_sell',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order_product',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
