# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-09 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_house_product_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_order',
            name='sKU',
        ),
    ]
