# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-24 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190724_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributor_sell',
            name='date',
        ),
        migrations.RemoveField(
            model_name='order_product',
            name='date',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='date',
        ),
    ]
