# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-09 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_customer_order_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_order',
            name='sKU',
            field=models.CharField(default='me', max_length=10),
            preserve_default=False,
        ),
    ]
