# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-24 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190724_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='month',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='year',
            field=models.DateField(auto_now=True),
        ),
    ]
