# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-24 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190724_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='month',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='year',
        ),
        migrations.AddField(
            model_name='distributor_sell',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order_product',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
