# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-24 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190724_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributor_sell',
            name='date',
        ),
        migrations.RemoveField(
            model_name='order_product',
            name='date',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='date',
        ),
        migrations.AddField(
            model_name='distributor_sell',
            name='month',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='distributor_sell',
            name='year',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='month',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
