# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-25 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190724_1601'),
        ('app', '0002_auto_20190724_1530'),
    ]

    operations = [
    ]
