# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-25 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190724_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor_sell',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order_product',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2019-10-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2019-01-01'),
            preserve_default=False,
        ),
    ]
