# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-26 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190725_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_serial', models.CharField(max_length=10)),
                ('sKU', models.CharField(max_length=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('month', models.PositiveIntegerField(default=0)),
                ('year', models.PositiveIntegerField(default=0)),
                ('date', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.House_Product')),
                ('warehouse', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Distributor')),
            ],
        ),
        migrations.RemoveField(
            model_name='distributor_sell',
            name='product',
        ),
        migrations.RemoveField(
            model_name='distributor_sell',
            name='warehouse',
        ),
        migrations.DeleteModel(
            name='Distributor_sell',
        ),
    ]
