# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-26 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_merge_20190725_1236'),
        ('app', '0013_auto_20190725_1958'),
    ]

    operations = [
    ]
