# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-30 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_prediction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='month',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
