# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-26 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_product_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_tax',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
