# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-26 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_customer_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_order',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
