# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-27 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20190727_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_order',
            name='customer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Customer'),
        ),
    ]
