# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-27 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20190727_1117'),
        ('app', '0014_merge_20190726_1007'),
    ]

    operations = [
    ]
