# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-27 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_invoice_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_order',
            name='discount',
        ),
    ]
