# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-27 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_merge_20190727_1437'),
        ('app', '0022_remove_customer_order_discount'),
    ]

    operations = [
    ]
